### PR TITLE
Add define delayed function macro.

### PR DESCRIPTION
**Pull request by justbur**
Useful for adding more delayed functions and having them behave
consistently.

### CODE REVIEW

**Comment by punassuming** [comment]
Thanks, any ideas of fxn besides `ranger-setup-preview` that would also benefit being delayed?

**Comment by justbur** [comment]
Not sure. I was just looking for lag and seeing if there was a function that could be delayed. `setup-preview` and `show-details` seemed to work well because they were called from `next-line` and `prev-line`. Any other commands that could be called quickly?

**Comment by justbur** [comment]
I'm getting much better performance just from these two, so you could probably leave it for now

**Comment by punassuming** [comment]
I did a benchmark with `elp` active for ranger and don't see much else that is taking a lot of time.  Will try more iterations and see if I can find anything.

**Comment by justbur** [comment]
Maybe you could get away with not loading the files in fundamental mode if you delayed the preview function like this?

**Comment by punassuming** [comment]
Possibly. we should still keep the option, but we can revert the default.

**Pull request merged**
