### PR TITLE
Turn off cursor in preview buffer

### PR DESCRIPTION
**Pull request by justbur**
I don't think there's any reason to show it

### CODE REVIEW

**Comment by punassuming** [comment]
I was thinking the same thing, but to turn off everywhere, seeing as we have hl-line enabled.

**Comment by justbur** [comment]
Someone might override that setting though right? You could have that as an option.

**Comment by punassuming** [comment]
If we explicitly set it during ranger-setup and ranger-subwindow, we shouldn't have a problem with the user overwriting.  We would just need to watch if we ever use wdired in the ranger buffer.  cursor-type should be buffer local anyway, so we dont need the setq-local, right?

**Comment by justbur** [comment]
True. I'd still make it an option. I don't think all themes support line
highlighting well.

**Pull request merged**
