### PR TITLE
Add "pl", "pL" commands for pasting symlinks

### PR DESCRIPTION
**Pull request by yuhan0**
Also refactor common code into separate function `ranger--invent-new-name`
for generating file names that would clash with existing files

### CODE REVIEW

**Comment by yuhan0** [comment]
Any news on this PR?
I noticed that this repo hasn't been updated for quite some time, are there any plans to maintain it or accept further contributions? Thanks :)

**Comment by punassuming** [comment]
Yes, sorry. I have been busy.  Was working on a new version but have had some trouble making it work nicely with some packages. Definitely accept contributions.

**Comment by yuhan0** [comment]
Ok, just rebased onto master to resolve conflicts - let me know if there's any other changes required

**Comment by punassuming** [comment]
Thanks! Only other thing would be to add the keys to the Readme.

**Comment by punassuming** [comment]
This has been merged in.  Thanks!

**Pull request closed without merging**
