### PR TITLE
Added documentation for people coming from dired

### PR DESCRIPTION
**Pull request by ryepesg**

### CODE REVIEW

**Comment by punassuming** [comment]
Thanks @ryepesg!  Looks like you submitted based off of a previous commit.   I can likely cherry pick it,  but if you are interested I can walk you through fixing the pull request.

**Comment by punassuming** [comment]
@ryepesg, I did a big update on the documentation,  please look over it and let me know which parts you would like to add.

**Comment by ryepesg** [comment]
Thanks @ralesi, where should I look for the changes you did? I would be very pleased to fixing the pull request with your help, I don't have previous experience with git, but I want to learn and I am willing to invest the time needed, thank you very much.

**Comment by punassuming** [comment]
To view the changes,  go here: https://github.com/ralesi/ranger.el/blob/master/README.md.  Checkout a new branch directly from master and revise this file to recommit

**Comment by ryepesg** [comment]
I tried two ways, a fresh one [here](https://github.com/ryepesg/ranger.el), and a new commit on the old one [here](https://github.com/ryepesg/ranger-old). Looking forward for new instructions please, to bring one of those to the pull request.

**Comment by vyp** [comment]
@ryepesg At https://github.com/ryepesg/ranger.el, click on "Pull Request" (just next to the "Compare" button), then click on "Create pull request".

**Comment by ryepesg** [comment]
Thank you @vyp. The new PR is at https://github.com/ralesi/ranger.el/pull/95/files.

**Comment by vyp** [comment]
@ryepesg No worries!

Also, because you say you want to learn git, I'm not sure, but sometimes the reason this happens is if your local copy of your fork was outdated compared to the version 'upstream' (in this case at https://github.com/ralesi/ranger.el). This can happen if you say, made an earlier contribution, then  in between the time between that contribution and another newer one, there have been further commits to the repository you are contributing to, but you don't update your local fork to reflect the changes made to the original repository before applying your new contribution.

Usually though, that even isn't really a problem, especially if there have only been a few new commits to the original repository, but it's still usually best to keep your local copy updated with the most recent changes to the original repository everytime you wish to make a new contribution.

To do this, you can simply `pull` from the original 'upstream' repository:

``` shell
$ git remote add upstream https://github.com/ralesi/ranger.el
$ git pull upstream master
```

The first line adds a new 'remote' called 'upstream'. A 'remote' is just sort of like the reference/name to a repository. So in this case, the remote is named 'upstream' and the repository url (via https) is https://github.com/ralesi/ranger.el. Of course, it doesn't have to be called 'upstream', I'm just suggesting it because I guess it's just convention.

You can have multiple remotes of course. If you check your `.git/config` file, you should see there's already a remote called 'origin' that points to https://github.com/ryepesg/ranger.el (assuming you used https to `clone` it). In fact, that `git remote add ...` command from above just edits this file, so, if you know what you're doing, you _could_ just edit this `.git/config` file directly without needing to run the command. ;)

The second line as you can see references this 'upstream' remote and 'pulls' from it. Pull is just a one-liner for fetch+merge. The 'master' is referring to the branch (in this case) which you want to `pull` from. Because a repository can have multiple branches of course, and git needs to know where exactly you want to pull from, so it's likely not enough to just specify the remote.

So if you're contributing to a branch other than 'master', you should change that 'master' to whatever branch name you want to pull from. (Also, if/when you're eventually making your pull request on the GitHub website, you would have to choose this branch there too, because I believe GitHub by default assumes you want to contribute to a repository's default branch, which is by default called 'master'.)

---

Also, this isn't related to anything above, but as a general tip, it's good to always make your contributions on a separate branch. This is so that you can open multiple unrelated pull requests to the same repository, without relying on one PR being dependent, or waiting on another. (e.g. Some of your PRs may be accepted, but some may also be rejected.)

Basically, before making your changes/commits, you should:

``` shell
$ git checkout -b mybranchname master
```

which creates a new branch called 'mybranchname' from the 'master' branch, and switches you to it. (e.g. for this pull request, a good branch name may be 'docs-dired' or something.) If you're contributing to a different branch than 'master', you should change 'master' to whatever branch name it is.

If you have already made your changes, but have not commited them yet, you can simply `git stash` to add these uncommited changes to the 'stash', run the above command to switch to the new branch, and then run `git stash pop` which re-applies those changes again. (Because you can't switch branches if you have uncommited changes.)

Then you can make your changes/commits as normal. When you want to push your commits to your fork in order to create the pull request, you should push to a remote branch of the same name:

``` shell
$ git push -u origin mybranchname
```

'origin' here is of course referring the original remote (i.e. on GitHub, these are usually called 'forks'). The `-u` is to set this 'origin mybranchname' as a tracking reference, so that any subsequent `git push`es will be pushed to this same place. (i.e. you would only need to run `git push` afterwards to push to the same place again.)

Then to create your pull request if you're using GitHub, you would just go to the your fork's page. Switch to the `mybranchname` branch by using the "Branch: ..." dropdown button, and click "Pull Request" or "New pull request" or whatever it is.

Eventually, once/if your pull request is ever merged or even rejected, it's a good idea to delete your 'mybranchname' branch. (So that it doesn't clutter up your list of branches as you continue contributing.) This can be done either on the pull request page itself if using GitHub, or if you're not, simply from the cli:

``` shell
$ git checkout master # First switch back to the default branch.
$ git branch -D mybranchname # Delete local branch.
$ git push origin --delete mybranchname # Delete remote branch (at 'origin' remote).
```

Do note though, that if your pull request was rejected, deleting the branch will remove your hard work for that pull request. (Whereas, if it was merged, it would generally be safe to delete because your contribution is now in the original repository anyway, and you would just `git checkout master` and `git pull upstream master` to see it again, assuming you contributed to the 'master' branch.) Nevertheless, it's still possible to [recover the deleted branch](http://stackoverflow.com/a/3640806) anyway.

Just a few small tips, but hopefully that makes sense and helps with your git learning!

**Comment by ryepesg** [comment]
@vyp what awesome explanation, it help me a lot, thank you!!!

**Pull request closed without merging**
