### PR TITLE
Auto detect binary files and prevent their preview

### PR DESCRIPTION
**Pull request by justbur**

### CODE REVIEW

**Comment by punassuming** [comment]
This is cool, I like what you did with the unless-and clause. 

Should we take binary files out of the exclude list?

**Comment by justbur** [comment]
> Should we take binary files out of the exclude list?

From what I understand, this is just a heuristic and won't catch every case. I'd leave the obvious extensions in the list. It's not a long list to check anyway.

**Comment by justbur** [comment]
Sorry I screwed up the commits. It should be fixed now

**Comment by punassuming** [comment]
Thanks, you can close this branch.

**Pull request merged**
